#spring:
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: r1
#            uri: http://localhost:8081/
#            predicates:
#              - Path=/customer/**
#          - id: r2
#            uri: http://localhost:8082/
#            predicates:
#              - Path=/accounts/**
#  application:
#    name: gateway-service
#server:
#  port: 8888
#
#
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE